### ISSUE TITLE
Provide a one-click Heroku deployment button

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-mailer#14]
https://devcenter.heroku.com/articles/heroku-button would help.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by Siddharth1006** [comment]
My name is Siddharth S.
I am a GSSOC'21 participant. If possible please assign this issue to me! I can work on this issue!

**Comment by AnandBaburajan** [comment]
> can you please assign this issue to me?

@subhangi2731 since you've shown interest in lots of issues, we would appreciate it if you chose and solved a few of them first. Thanks!

**Comment by Siddharth1006** [comment]
I had exams until yesterday. @AnandBaburajan If possible can you please provide me one more day. I am trying to work on this issue. Will try to submit the PR as soon as possible.

**Comment by AnandBaburajan** [comment]
> If possible can you please provide me one more day.

Hey, hakuna matata! I've an exam tomorrow too, haha.

> I am trying to work on this issue.

Thank you! :)

**Comment by AnandBaburajan** [comment]
@Siddharth1006 if you're still interested, pls let us know and also share what you plan to do, your doubts, etc, thanks!

**Comment by AnandBaburajan** [comment]
Closing this PR since we're discontinuing the mailer service. Thanks for showing interest. :)
