### ISSUE TITLE
Improve the e-mail templates. 

### ISSUE THREAD

**Issue by AthulJoshi** [RocketMeet/RocketMeet-mailer#15]
The current templates are just basic ones. More improvements can be made.

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by AthulJoshi** [comment]
@subhangi2731 I've assigned the issue to you.

**Comment by AnandBaburajan** [comment]
@subhangi2731 since you've shown interest in lots of issues, you've been unassigned from this one. Please get in touch with us at our Gitter chatroom to let us know which issues you're actually interested in. Thanks!

**Comment by savi-1311** [comment]
Can you please assign this to me? Would like to work on this one!
And any specifications on the color scheme or the theme of the template required?

**Comment by AnandBaburajan** [comment]
Hey @savi-1311, thanks! Please join our Gitter chatroom too! Feel free to come up with template ideas and share them here!

**Comment by AnandBaburajan** [comment]
Closing this PR since we're discontinuing the mailer service. Thanks for showing interest. :)
