### ISSUE TITLE
Containerize RocketMeet-mailer

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-mailer#16]
https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md would help too.

**Comment by Siddharth1006** [comment]
My name is Siddharth . I am a GSSOC'21 participant. If possible, please asssign this issue to me!

**Comment by AnandBaburajan** [comment]
Hey @Siddharth1006! Welcome and thanks! You're suggested to join our Gitter chatroom too! Link can be found in our readme.

**Comment by AnandBaburajan** [comment]
@Siddharth1006 if you're still interested, pls let us know and also share what you plan to do, thanks!

**Comment by mdPial** [comment]
I would like to work on that issue.

**Comment by AnandBaburajan** [comment]
> I would like to work on that issue.

Cool! You might find this https://github.com/RocketMeet/RocketMeet-server/pull/38 helpful.

**Comment by mdPial** [comment]
> > I would like to work on that issue.
> 
> Cool! You might find this [RocketMeet/RocketMeet-server#38](https://github.com/RocketMeet/RocketMeet-server/pull/38) helpful.

Thank you  😄

**Comment by mdPial** [comment]
I am busy with my final exam. Will take more than 7 days to work on this issue again.😅 If anyone is interested you can assign this issue.

**Comment by AnandBaburajan** [comment]
> I am busy with my final exam. Will take more than 7 days to work on this issue again. If anyone is interested you can assign this issue.

Hakuna matata - this might be a bit challenging for you but it's also not on our urgent 'todo' list (https://github.com/RocketMeet/RocketMeet-client/milestone/1) so you've plenty of time and can work on this whenever you're free. The PR by @PushkarDureja at the server would definitely help too.

**Comment by AnandBaburajan** [comment]
Closing this PR since we're discontinuing the mailer service. Thanks for showing interest. :)
