### ISSUE TITLE
Setup a Github action to show ESLint errors in PRs

### ISSUE THREAD

**Issue by AnandBaburajan** [RocketMeet/RocketMeet-mailer#17]
Here's an option: https://dev.to/jnybgr/how-to-visualize-eslint-errors-on-github-3f8p. Feel free to share better ones!

**Comment by mdPial** [comment]
I would like to work on that issue

**Comment by AnandBaburajan** [comment]
Thanks @mdPial!

**Comment by mdPial** [comment]
It's my pleasure.

**Comment by mdPial** [comment]
> Here's an option: https://dev.to/jnybgr/how-to-visualize-eslint-errors-on-github-3f8p. Feel free to share better ones!

I have tried the mentioned approach. That approach is not well detailed. I have tried other approaches too. I found this approach is very simple https://github.com/reviewdog/action-eslint 
and results are pretty same.
I have tested in my forked repository. Here is the link of my test PR in my forked repo https://github.com/mdPial/RocketMeet-mailer/pull/6
Could I setup using this approach?
![image](https://user-images.githubusercontent.com/43095489/110907069-0b3e3c00-8337-11eb-8bd6-6d76bf23fcd1.png)

**Comment by AnandBaburajan** [comment]
> Could I setup using this approach?

Sounds good, go ahead! @aysp-99 maybe you would like this approach too for the client.

**Comment by aysp-99** [comment]
> > Could I setup using this approach?
> 
> Sounds good, go ahead! @aysp-99 maybe you would like this approach too for the client.

Sure. I saw it before, just wanted to see if it can be implemented using the method mentioned in issue description. I will use the latter method to implement it. Thanks!
